import "./App.css";
import Viewer from "../../src/components/Viewer";
import img1 from "./assets/girl1.jpg";
import img2 from "./assets/girl2.png";
import img3 from "./assets/girl3.jpg";
import img4 from "./assets/girl4.jpg";
import img5 from "./assets/girl5.jpg";

function App() {
  return (
    <>
      <h1>My Gallery</h1>
      <div className="App">
        <Viewer className="view">
          <div>
            <img src={img1} alt="Image of a school girl, generated by AI" />
          </div>
          <div>
            <img src={img2} alt="image 02" />
          </div>
          <div>
            <img src={img3} alt="image 03" />
          </div>
          <div>
            <img src={img4} alt="image 03" />
          </div>
          <div>
            <img src={img5} alt="image 03" />
          </div>
        </Viewer>
      </div>
    </>
  );
}

export default App;
