import Viewer from "./components/Viewer";
import img1 from "./assets/img1.jpeg";
import img2 from "./assets/img2.jpg";
import img3 from "./assets/img3.jpg";
import img4 from "./assets/gallery_01.jpg";

import styles from "./App.module.css";
function App() {
  return (
    <>
      <div className={styles.ImageContainer}>
        <Viewer controls={false} className="v">
          <div>
            <img src={img1} alt="Image of a school girl, generated by ia" />
          </div>
          <div>
            <img src={img2} alt="image 02" />
          </div>
          <div>
            <img src={img3} alt="image of a girl generated by ia" />
          </div>
          <div>
            <img src={img4} alt="Gym girl" />
          </div>
        </Viewer>
      </div>
    </>
  );
}

export default App;
